### ISSUE TITLE
Unify CI and Trigger on Pull Request

### ISSUE THREAD

**Issue by MSevey** [celestiaorg/celestia.org_older#210]
The CI is a copy paste except for the branch name which I believe just relates to the target directory [here](https://github.com/celestiaorg/celestia.org/blob/main/.github/workflows/main.yml#L50).

```[tasklist]
### Tasks
- [ ] Unify to one file
- [ ] Add `pull_request` as a trigger
- [ ] Only run the deploy step on push events on `main` and `dev` branches or `workflow_dispatch` triggers
- [ ] set the target directory conditionally based on the branch name
- [ ] Add comment that `workflow_dispatch` trigger only works on the default branch so can't be used for the dev branch deployment
```

**Comment by MSevey** [comment]
deprioritized
